# Generated by Django 5.0.9 on 2024-12-06 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('procesos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horasprocesos',
            fields=[
                ('id_hrspro', models.AutoField(db_column='ID_HrsProcesos', primary_key=True, serialize=False)),
                ('fecha_hrspro', models.DateField(db_column='Fecha_HrsProcesos')),
                ('asistencia', models.CharField(blank=True, db_column='Asistencia', max_length=10, null=True)),
                ('id_pro', models.IntegerField(blank=True, db_column='ID_Proceso', null=True)),
                ('horaentrada', models.TimeField(blank=True, db_column='HoraEntrada', null=True)),
                ('horasalida', models.TimeField(blank=True, db_column='HoraSalida', null=True)),
                ('hrs', models.FloatField(blank=True, db_column='Hrs', null=True)),
                ('totalhrs', models.FloatField(blank=True, db_column='TotalHrs', null=True)),
                ('hrsextras', models.FloatField(blank=True, db_column='HrsExtras', null=True)),
                ('id_producto', models.CharField(blank=True, max_length=10, null=True)),
                ('autorizado', models.BooleanField(db_column='Autorizado')),
                ('sync', models.BooleanField(db_column='SYNC')),
                ('ucreado', models.CharField(blank=True, db_column='UCreado', max_length=20, null=True)),
                ('umod', models.CharField(blank=True, db_column='UMod', max_length=20, null=True)),
                ('fmod', models.DateField(db_column='FMod', null=True)),
                ('codigo_emp', models.ForeignKey(db_column='Codigo_Emp', on_delete=django.db.models.deletion.DO_NOTHING, related_name='horasprocesos_horas', to='procesos.empleados')),
            ],
            options={
                'db_table': 'HorasProcesos',
                'managed': True,
            },
        ),
    ]
