# Generated by Django 5.0.9 on 2024-12-06 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('codigo_emp', models.CharField(db_column='Codigo_Emp', max_length=50, primary_key=True, serialize=False)),
                ('nombre_emp', models.CharField(db_column='Nombre_Emp', max_length=100)),
                ('depto_emp', models.CharField(db_column='Depto_Emp', max_length=60)),
                ('puesto_emp', models.CharField(db_column='Puesto_Emp', max_length=100)),
                ('tipo_puesto', models.CharField(db_column='Tipo_Puesto', max_length=50)),
                ('turno_emp', models.CharField(blank=True, db_column='Turno_Emp', max_length=30, null=True)),
                ('supervisor', models.CharField(blank=True, db_column='Supervisor', max_length=6, null=True)),
            ],
            options={
                'db_table': 'Empleados',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Procesos',
            fields=[
                ('id_pro', models.AutoField(db_column='ID_Pro', primary_key=True, serialize=False)),
                ('nombre_pro', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Nombre_Pro', max_length=100)),
                ('estado_pro', models.BooleanField(db_column='Estado_Pro', default=True)),
            ],
            options={
                'db_table': 'Procesos',
            },
        ),
    ]
